const IMGS={"alphaboost":"https://rocket-league.com/content/media/items/avatar/220px/a943e71c601436141243.png","alphaboost_black":"https://rocket-league.com/content/media/items/avatar/220px/a943e71c601436141243.png","alphaboost_purple":"https://rocket-league.com/content/media/items/avatar/220px/a943e71c601436141243.png","alphaboost_red":"https://rocket-league.com/content/media/items/avatar/220px/a943e71c601436141243.png","alphaboost_white":"https://rocket-league.com/content/media/items/avatar/220px/a943e71c601436141243.png","decal_fennec_20xx":"https://rocket-league.com/content/media/items/avatar/220px/a9b3b8f4071490226029.png","decal_fennec_diss":"https://rocket-league.com/content/media/items/avatar/220px/56cea301ef1522777420.png","decal_fennec_slip":"https://rocket-league.com/content/media/items/avatar/220px/342148e9851473411817.png","decal_fennec_afflu":"https://rocket-league.com/content/media/items/avatar/220px/0c3d77c64e1655298033.png","decal_fennec_neural":"https://rocket-league.com/content/media/items/avatar/220px/15060304171637113943.png","decal_oct_20xx":"https://rocket-league.com/content/media/items/avatar/220px/a9b3b8f4071490226029.png","decal_oct_slip":"https://rocket-league.com/content/media/items/avatar/220px/342148e9851473411817.png","decal_oct_storm":"https://rocket-league.com/content/media/items/avatar/220px/ccc65d49891518049453.png","decal_oct_diss":"https://rocket-league.com/content/media/items/avatar/220px/56cea301ef1522777420.png","decal_oct_heat":"https://rocket-league.com/content/media/items/avatar/220px/e574121eb11473421648.png","decal_oct_neural":"https://rocket-league.com/content/media/items/avatar/220px/15060304171637113943.png","goal_atomizer":"https://rocket-league.com/content/media/items/avatar/220px/8a7b232a1f1522776922.png","goal_electroshock":"https://rocket-league.com/content/media/items/avatar/220px/c968ab9a051499318860.png","goal_hellfire":"https://rocket-league.com/content/media/items/avatar/220px/2edd5c32581499318998.png","goal_reaper":"https://rocket-league.com/content/media/items/avatar/220px/9e6fc7a8151508198121.png","goal_dueling":"https://rocket-league.com/content/media/items/avatar/220px/b50e027ce81512417574.png","goal_dueling_anodized":"https://rocket-league.com/content/media/items/avatar/220px/b8eb5616051678271098.png","wheel_cristiano":"https://rocket-league.com/content/media/items/avatar/220px/a67e907fb81451699877.png","wheel_goldstone":"https://rocket-league.com/content/media/items/avatar/220px/8b17e66d471509567593.png","antenna_betanugget":"https://rocket-league.com/content/media/items/avatar/220px/fdde2fd5781520346332.png"};

const CATALOG = [
  {
    "id": 1,
    "name": "AlphaBoost",
    "cat": "Boosts",
    "rar": "Black Market",
    "img": "alphaboost",
    "folder": "boosts/alphaboost",
    "upk": "Boost_Standard_SF.upk",
    "target": "Boost_Standard_SF.upk",
    "car": "All",
    "desc": "O lendário Alpha Boost (Gold Rush). Dado apenas a testadores da Alpha em 2015. Um dos itens mais raros do Rocket League."
  },
  {
    "id": 2,
    "name": "AlphaBoost Black",
    "cat": "Boosts",
    "rar": "Black Market",
    "img": "alphaboost_black",
    "folder": "boosts/alphaboost black",
    "upk": "Boost_Standard_SF.upk",
    "target": "Boost_Standard_SF.upk",
    "car": "All",
    "desc": "Variante Black do Alpha Boost. Efeito de chama dourada com fundo preto."
  },
  {
    "id": 3,
    "name": "AlphaBoost Purple",
    "cat": "Boosts",
    "rar": "Black Market",
    "img": "alphaboost_purple",
    "folder": "boosts/alphaboost purple",
    "upk": "Boost_Standard_SF.upk",
    "target": "Boost_Standard_SF.upk",
    "car": "All",
    "desc": "Variante Purple do Alpha Boost com efeito dourado roxo."
  },
  {
    "id": 4,
    "name": "AlphaBoost Red",
    "cat": "Boosts",
    "rar": "Black Market",
    "img": "alphaboost_red",
    "folder": "boosts/alphaboost red",
    "upk": "Boost_Standard_SF.upk",
    "target": "Boost_Standard_SF.upk",
    "car": "All",
    "desc": "Variante Crimson/Red do Alpha Boost."
  },
  {
    "id": 5,
    "name": "AlphaBoost White",
    "cat": "Boosts",
    "rar": "Black Market",
    "img": "alphaboost_white",
    "folder": "boosts/alphaboost white",
    "upk": "Boost_Standard_SF.upk",
    "target": "Boost_Standard_SF.upk",
    "car": "All",
    "desc": "Variante Titanium White do Alpha Boost. Extremamente raro."
  },
  {
    "id": 6,
    "name": "20XX (Fennec)",
    "cat": "Decals",
    "rar": "Black Market",
    "img": "decal_fennec_20xx",
    "folder": "decals/fennec/20XX",
    "upk": "skin_grain_flames_SF.upk",
    "target": "skin_grain_flames_SF.upk",
    "car": "Fennec",
    "desc": "Decal animado 20XX no Fennec. Black Market animado com efeito de energia elétrica azul."
  },
  {
    "id": 7,
    "name": "Dissolver (Fennec)",
    "cat": "Decals",
    "rar": "Black Market",
    "img": "decal_fennec_diss",
    "folder": "decals/fennec/Dissolver",
    "upk": "skin_grain_flames_SF.upk",
    "target": "skin_grain_flames_SF.upk",
    "car": "Fennec",
    "desc": "Dissolver animado no Fennec. Efeito de dissolução com cores vibrantes."
  },
  {
    "id": 8,
    "name": "Slipstream (Fennec)",
    "cat": "Decals",
    "rar": "Black Market",
    "img": "decal_fennec_slip",
    "folder": "decals/fennec/Slipstream",
    "upk": "skin_grain_flames_SF.upk",
    "target": "skin_grain_flames_SF.upk",
    "car": "Fennec",
    "desc": "Slipstream animado no Fennec. Ondas de velocidade em loop contínuo."
  },
  {
    "id": 9,
    "name": "Affluenter (Fennec)",
    "cat": "Decals",
    "rar": "Import",
    "img": "decal_fennec_afflu",
    "folder": "decals/fennec/affluenter",
    "upk": "skin_grain_flames_SF.upk",
    "target": "skin_grain_flames_SF.upk",
    "car": "Fennec",
    "desc": "Decal Affluenter exclusivo para Fennec. Design geométrico Import."
  },
  {
    "id": 10,
    "name": "Neural Network (Fennec)",
    "cat": "Decals",
    "rar": "Black Market",
    "img": "decal_fennec_neural",
    "folder": "decals/fennec/neural network",
    "upk": "skin_grain_flames_SF.upk",
    "target": "skin_grain_flames_SF.upk",
    "car": "Fennec",
    "desc": "Neural Network animado no Fennec. Efeito de rede neural pulsante."
  },
  {
    "id": 11,
    "name": "20XX (Octane)",
    "cat": "Decals",
    "rar": "Black Market",
    "img": "decal_oct_20xx",
    "folder": "decals/octane/20XX",
    "upk": "Skin_Octane_Wings_SF.upk",
    "target": "Skin_Octane_Wings_SF.upk",
    "car": "Octane",
    "desc": "Decal animado 20XX no Octane. Clássico Black Market com energia elétrica."
  },
  {
    "id": 12,
    "name": "Slipstream (Octane)",
    "cat": "Decals",
    "rar": "Black Market",
    "img": "decal_oct_slip",
    "folder": "decals/octane/Slipstream",
    "upk": "Skin_Octane_Wings_SF.upk",
    "target": "Skin_Octane_Wings_SF.upk",
    "car": "Octane",
    "desc": "Slipstream animado no Octane. Ondas de velocidade em azul e roxo."
  },
  {
    "id": 13,
    "name": "Storm Watch (Octane)",
    "cat": "Decals",
    "rar": "Black Market",
    "img": "decal_oct_storm",
    "folder": "decals/octane/Storm Watch",
    "upk": "Skin_Octane_Wings_SF.upk",
    "target": "Skin_Octane_Wings_SF.upk",
    "car": "Octane",
    "desc": "Storm Watch animado no Octane. Tempestade elétrica em movimento."
  },
  {
    "id": 14,
    "name": "Dissolver (Octane)",
    "cat": "Decals",
    "rar": "Black Market",
    "img": "decal_oct_diss",
    "folder": "decals/octane/dissolver",
    "upk": "Skin_Octane_Wings_SF.upk",
    "target": "Skin_Octane_Wings_SF.upk",
    "car": "Octane",
    "desc": "Dissolver animado no Octane. Um dos decals mais icônicos do RL."
  },
  {
    "id": 15,
    "name": "Heatwave (Octane)",
    "cat": "Decals",
    "rar": "Black Market",
    "img": "decal_oct_heat",
    "folder": "decals/octane/heatwave",
    "upk": "Skin_Octane_Wings_SF.upk",
    "target": "Skin_Octane_Wings_SF.upk",
    "car": "Octane",
    "desc": "Heatwave animado no Octane. O primeiro Black Market decal animado do jogo."
  },
  {
    "id": 16,
    "name": "Neural Network (Octane)",
    "cat": "Decals",
    "rar": "Black Market",
    "img": "decal_oct_neural",
    "folder": "decals/octane/neural network",
    "upk": "Skin_Octane_Wings_SF.upk",
    "target": "Skin_Octane_Wings_SF.upk",
    "car": "Octane",
    "desc": "Neural Network animado no Octane. Design futurista de rede neural."
  },
  {
    "id": 17,
    "name": "Atomizer",
    "cat": "Goal Explosions",
    "rar": "Import",
    "img": "goal_atomizer",
    "folder": "goal explosion/Atomizer",
    "upk": "Explosion_Default_SF.upk",
    "target": "Explosion_Default_SF.upk",
    "car": "All",
    "desc": "Atomizer — explosão de gol que desintegra o campo em partículas de energia."
  },
  {
    "id": 18,
    "name": "Electroshock",
    "cat": "Goal Explosions",
    "rar": "Import",
    "img": "goal_electroshock",
    "folder": "goal explosion/Electroshock",
    "upk": "Explosion_Default_SF.upk",
    "target": "Explosion_Default_SF.upk",
    "car": "All",
    "desc": "Electroshock — descarga elétrica massiva ao marcar um gol."
  },
  {
    "id": 19,
    "name": "Hellfire",
    "cat": "Goal Explosions",
    "rar": "Import",
    "img": "goal_hellfire",
    "folder": "goal explosion/Hellfire",
    "upk": "Explosion_Default_SF.upk",
    "target": "Explosion_Default_SF.upk",
    "car": "All",
    "desc": "Hellfire — explosão de fogo infernal que envolve toda a área do gol."
  },
  {
    "id": 20,
    "name": "Reaper",
    "cat": "Goal Explosions",
    "rar": "Import",
    "img": "goal_reaper",
    "folder": "goal explosion/Reaper",
    "upk": "Explosion_Default_SF.upk",
    "target": "Explosion_Default_SF.upk",
    "car": "All",
    "desc": "Reaper — a foice da morte ceifa o campo ao marcar um gol épico."
  },
  {
    "id": 21,
    "name": "Dueling Dragons",
    "cat": "Goal Explosions",
    "rar": "Black Market",
    "img": "goal_dueling",
    "folder": "goal explosion/dueling dragons",
    "upk": "Explosion_Default_SF.upk",
    "target": "Explosion_Default_SF.upk",
    "car": "All",
    "desc": "Dueling Dragons — dois dragões se enfrentam em uma explosão épica de gol."
  },
  {
    "id": 22,
    "name": "Dueling Dragons Anodized",
    "cat": "Goal Explosions",
    "rar": "Black Market",
    "img": "goal_dueling_anodized",
    "folder": "goal explosion/dueling dragons anodized",
    "upk": "Explosion_Default_SF.upk",
    "target": "Explosion_Default_SF.upk",
    "car": "All",
    "desc": "Dueling Dragons Anodized — versão metálica e dourada dos Dueling Dragons."
  },
  {
    "id": 23,
    "name": "Cristiano",
    "cat": "Wheels",
    "rar": "Import",
    "img": "wheel_cristiano",
    "folder": "wheels/cristiano",
    "upk": "WHEEL_Hydra_SF.upk",
    "target": "WHEEL_Hydra_SF.upk",
    "car": "All",
    "desc": "Cristiano — rodas deluxe clássicas do Rocket League. Design limpo e elegante."
  },
  {
    "id": 24,
    "name": "Goldstone",
    "cat": "Wheels",
    "rar": "Black Market",
    "img": "wheel_goldstone",
    "folder": "wheels/goldstone",
    "upk": "WHEEL_Hydra_SF.upk",
    "target": "WHEEL_Hydra_SF.upk",
    "car": "All",
    "desc": "Goldstone — rodas Alpha douradas. Recompensa exclusiva dos testadores Alpha de 2015."
  },
  {
    "id": 25,
    "name": "Beta Nugget",
    "cat": "Antennas",
    "rar": "Very Rare",
    "img": "antenna_betanugget",
    "folder": "antennas/beta nugget",
    "upk": "Antenna_SoccerBall_SF.upk",
    "target": "Antenna_SoccerBall_SF.upk",
    "car": "All",
    "desc": "Gold Nugget — antena exclusiva dos testadores Beta de 2015. Pepita de ouro dourada."
  }
];
